name: Build Project
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    environment: "default"
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: ${{env.POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{env.POSTGRES_PASSWORD}}
      POSTGRES_DB: ${{env.POSTGRES_DB}}
    services:
      postgres:
        image: postgres:latest
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: ${{env.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{env.POSTGRES_PASSWORD}}
          POSTGRES_DB: ${{env.POSTGRES_DB}}
    steps:
      - name: clone
        uses: actions/download-artifact@v5
      - name: setup
        uses: actions/setup-java@v4
        with:
          java-version: "25"
          distribution: "temurin"
          architecture: "x64"
          cache: 'maven'
      - name: build
        id: build
        run: mvn package



